export const companies_information = [
    {
      company_id: "kwideo-finance",
      company_name: "Kwideo",
      stock_name: "BlackRock Advantage Trust",
      stock_symbol: "BLR",
      industry: "finance",
      market_cap: "350B",
      currency: "USD",
      popularityIndex: 3,
    },
    {
      company_id: "tekfly-finance",
      company_name: "Tekfly",
      stock_name: "FORM Holdings Corp.",
      stock_symbol: "FH",
      industry: "finance",
      market_cap: "32.87B",
      currency: "USD",
      popularityIndex: 22,
    },
    {
      company_id: "feedbug-finance",
      company_name: "Feedbug",
      stock_name: "Acushnet Holdings Corp.",
      stock_symbol: "GOLF",
      industry: "finance",
      market_cap: "1.42",
      currency: "EUR",
      popularityIndex: 88,
    },
    {
      company_id: "twinder-computer-software",
      company_name: "Twinder",
      stock_name: "FalconStor Software, Inc.",
      stock_symbol: "FALC",
      industry: "computer-software",
      market_cap: "17.44B",
      currency: "EUR",
      popularityIndex: 45,
    },
    {
      company_id: "bubletube-banking-software",
      company_name: "Bubbletube",
      stock_name: "FIRST REPUBLIC BANK",
      stock_symbol: "FRC",
      industry: "banking-services",
      market_cap: "128.1B",
      currency: "EUR",
      popularityIndex: 47,
    },
    {
      company_id: "livetube-computer-software",
      company_name: "Livetube",
      stock_name: "Pure Cycle Corporation",
      stock_symbol: "PCYO",
      industry: "computer-software",
      market_cap: "188.2B",
      currency: "USD",
      popularityIndex: 23,
    },
    {
      company_id: "wordtube-computer-software",
      company_name: "Wordtune",
      stock_name: "Luxfer Holdings PLC",
      stock_symbol: "LXFR",
      industry: "computer-software",
      market_cap: "12.14B",
      currency: "EUR",
      popularityIndex: 32,
    },
    {
      company_id: "eabox-banking-services",
      company_name: "Eabox",
      stock_name: "InnerWorkings, Inc.",
      stock_symbol: "INWK",
      industry: "banking-services",
      market_cap: "53B",
      currency: "EUR",
      popularityIndex: 39,
    },
    {
      company_id: "zoombeat-multi-sector-company",
      company_name: "Zoombeat",
      stock_name: "Allot Communications Ltd.",
      stock_symbol: "ALLT",
      industry: "multi-sector-company",
      market_cap: "159.8B",
      currency: "RUB",
      popularityIndex: 41,
    },
    {
      company_id: "twitternation-multi-sector-company",
      company_name: "Twitternation",
      stock_name: "Axovant Sciences Ltd.",
      stock_symbol: "INWK",
      industry: "multi-sector-company",
      market_cap: "583B",
      currency: "EUR",
      popularityIndex: 55,
    },
    {
      company_id: "fanoodle-multi-sector-company",
      company_name: "Fanoodle",
      stock_name: "Natus Medical Incorporated",
      stock_symbol: "NAT",
      industry: "multi-sector-company",
      market_cap: "12.77B",
      currency: "RUB",
      popularityIndex: 58,
    },
    {
      company_id: "flipopia-multi-sector-company",
      company_name: "Flipopia",
      stock_name: "Marathon Patent Group, Inc.",
      stock_symbol: "MAR",
      industry: "multi-sector-company",
      market_cap: "66.7B",
      currency: "USD",
      popularityIndex: 64,
    },
    {
      company_id: "skipfire-computer-software",
      company_name: "Skipfire",
      stock_name: "Nuveen Mortgage Fund",
      stock_symbol: "JLC",
      industry: "computer-software",
      market_cap: "55B",
      currency: "EUR",
      popularityIndex: 67,
    },
    {
      company_id: "vrowsezoom-banking-services",
      company_name: "Browsezoom",
      stock_name: "Magellan Health, Inc.",
      stock_symbol: "MAG",
      industry: "banking-services",
      market_cap: "8B",
      currency: "USD",
      popularityIndex: 79,
    },
  ];
  
 export const company_stock_prices = {
    "vrowsezoom-banking-services": {
      price: 185,
      volume: "UP",
    },
    "skipfire-computer-software": {
      price: 175,
      volume: "DOWN",
    },
    "flipopia-multi-sector-company": {
      price: 77,
      volume: "UP",
    },
    "fanoodle-multi-sector-company": {
      price: 1877,
      volume: "UP",
    },
    "twitternation-multi-sector-company": {
      price: 2943,
      volume: "DOWN",
    },
    "kwideo-finance": {
      price: 44,
      volume: "UP",
    },
    "tekfly-finance": {
      price: 18,
      volume: "DOWN",
    },
    "bubletube-banking-software": {
      price: 97,
      volume: "UP",
    },
    "eabox-banking-services": {
      price: 54,
      volume: "DOWN",
    },
  };
  